In [1]:
import sys
sys.path.insert(0, '/home/mariia/AstroML/')
sys.path.insert(0, '/home/mariia/AstroML/src/')

In [2]:
from datasets import load_dataset
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import wandb
from tqdm import tqdm
import pandas as pd
import torch
import time
from torch.utils.data.sampler import BatchSampler, RandomSampler

from src.data import get_datasets
from dev.core.dataset import PSMDataset

In [3]:
CLASSES = ['EW', 'SR', 'EA', 'RRAB', 'EB', 'ROT', 'RRC', 'HADS', 'M', 'DSCT']

In [22]:
api = wandb.Api()
run = api.run('AstroCLIPResults3/runs/amfm6esw')
config = run.config

old_ds = PSMDataset(run.config, split='train')

In [21]:
ds, _, _ = get_datasets('MeriDK/AstroM3Processed', 'sub10_42', 200)

Map:   0%|          | 0/210 [00:00<?, ? examples/s]

Map:   0%|          | 0/220 [00:00<?, ? examples/s]

In [25]:
for i in range(10):
    # el1 = old_ds[i][2]
    # el2 = ds[i]['spectra']
    print(old_ds[i][-1], ds[i]['label'])

1 tensor(1)
4 tensor(4)
9 tensor(9)
9 tensor(9)
8 tensor(8)
0 tensor(0)
7 tensor(7)
8 tensor(8)
0 tensor(0)
4 tensor(4)


In [24]:
el1[:, 0]

array([-7.9832220e-01,  2.6483824e-09,  2.5710573e+00], dtype=float32)

In [25]:
el2[:, 0]

tensor([2.4209e+00, 1.1009e-08, 3.2554e+00])

In [14]:
df = pd.read_csv('/home/mariia/AstroM3Dataset/splits/sub10/0/train.csv')

In [21]:
(df['spec_filename'] == old_ds.df['spec_filename']).all()

True

In [33]:
old_ds.df['target']

0         EW
1         EA
2       DSCT
3         EB
4         EA
        ... 
1655    DSCT
1656    DSCT
1657     ROT
1658     RRC
1659     ROT
Name: target, Length: 1660, dtype: object

In [5]:
def crop_or_pad_photometry(example):
    seq_len = 200
    X = example['photometry']

    if X.shape[0] > seq_len:
        X = X[:seq_len]
    elif X.shape[0] < seq_len:
        pad_size = (0, 0, 0, seq_len - X.shape[0])
        X = torch.nn.functional.pad(X, pad_size, 'constant', 0)

    example['photometry'] = X
    
    return example

In [6]:
def crop_or_pad_spectra(example):
    seq_len = 2575
    X = example['spectra']

    if X.shape[0] > seq_len:
        X = X[:seq_len]
    elif X.shape[0] < seq_len:
        pad_size = (0, 0, 0, seq_len - X.shape[0])
        X = torch.nn.functional.pad(X, pad_size, 'constant', 0)

    example['spectra'] = X
    
    return example

In [39]:
ds = load_dataset('MeriDK/AstroM3Processed', name='full_42', split='train')
ds = ds.with_format('torch')
ds = ds.map(crop_or_pad_photometry, num_proc=16)
ds = ds.map(crop_or_pad_spectra, num_proc=16)

Map (num_proc=16):   0%|          | 0/17063 [00:00<?, ? examples/s]

Map (num_proc=16):   0%|          | 0/17063 [00:00<?, ? examples/s]

In [40]:
ds = ds.cast_column('photometry', datasets.Array2D(shape=(None, 3), dtype='float32'))
ds = ds.cast_column('spectra', datasets.Array2D(shape=(None, 3), dtype='float32'))

Casting the dataset:   0%|          | 0/17063 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/17063 [00:00<?, ? examples/s]

In [41]:
dl = DataLoader(ds, batch_size=128, shuffle=False, num_workers=4)

In [42]:
start = time.time()

for batch in tqdm(dl):
    pass

time.time() - start

100%|███████████████████████████████████████████████████████████████████████████████████████| 134/134 [00:12<00:00, 11.04it/s]


12.146114826202393

In [10]:
dl = DataLoader(ds, batch_size=128, shuffle=False, num_workers=8)
start = time.time()
for batch in tqdm(dl):
    pass
time.time() - start

100%|█████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:16<00:00,  1.24s/it]


16.073495864868164

In [13]:
dl = DataLoader(ds, batch_size=128, shuffle=False, num_workers=13)
start = time.time()
for batch in tqdm(dl):
    pass
time.time() - start

100%|█████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:11<00:00,  1.10it/s]


11.821810007095337

In [14]:
start = time.time()
for batch in tqdm(ds.iter(batch_size=128)):
    pass
time.time() - start

13it [01:11,  5.48s/it]


71.2034764289856

In [17]:
ds.iter

<bound method Dataset.iter of Dataset({
    features: ['photometry', 'spectra', 'metadata', 'label'],
    num_rows: 1660
})>

In [34]:
ds = load_dataset('MeriDK/AstroM3Processed', name='sub10_42')
ds = ds.cast_column('photometry', datasets.Array2D(shape=(None, 3), dtype='float32'))
ds = ds.cast_column('spectra', datasets.Array2D(shape=(None, 3), dtype='float32'))
hf = HFPSMDataset(ds, CLASSES, 200)
dl = DataLoader(hf, batch_size=128, shuffle=False, num_workers=4)

Casting the dataset:   0%|          | 0/1660 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/210 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/220 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/1660 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/210 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/220 [00:00<?, ? examples/s]

In [35]:
start = time.time()

for batch in tqdm(dl):
    pass

time.time() - start

100%|█████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.30it/s]


5.668868541717529

In [18]:
api = wandb.Api()
run = api.run('AstroCLIPOptuna3/0r838fa4')
config = run.config
config['mode'] = 'all'
config['file'] = 'preprocessed_data/sub10_lb0/spectra_and_v'

old_ds = PSMDataset(run.config, split='train')

In [19]:
dl = DataLoader(old_ds, batch_size=128, shuffle=False, num_workers=4)

start = time.time()

for batch in tqdm(dl):
    pass

time.time() - start

100%|█████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:33<00:00,  2.61s/it]


33.89448046684265

In [20]:
ds = load_dataset('MeriDK/AstroM3Processed', name='sub10_42', split='train', keep_in_memory=True)
ds = ds.with_format('torch')
ds = ds.map(crop_or_pad_photometry, num_proc=16)
ds = ds.map(crop_or_pad_spectra, num_proc=16)
dl = DataLoader(ds, batch_size=128, shuffle=False, num_workers=4)

start = time.time()
for batch in tqdm(dl):
    pass
time.time() - start

Map (num_proc=16):   0%|          | 0/1660 [00:00<?, ? examples/s]

Map (num_proc=16):   0%|          | 0/1660 [00:00<?, ? examples/s]

100%|█████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:23<00:00,  1.82s/it]


23.70095992088318

In [23]:
dl = DataLoader(ds, batch_size=128, shuffle=False, num_workers=4, pin_memory=True)
start = time.time()
for batch in tqdm(dl):
    pass
time.time() - start

100%|█████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:23<00:00,  1.83s/it]


23.802693128585815

In [24]:
start = time.time()
for batch in tqdm(dl):
    pass
time.time() - start

100%|█████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:27<00:00,  2.12s/it]


27.528242349624634

In [32]:
ds.features

{'photometry': Sequence(feature=Sequence(feature=Value(dtype='float32', id=None), length=3, id=None), length=-1, id=None),
 'spectra': Sequence(feature=Sequence(feature=Value(dtype='float32', id=None), length=3, id=None), length=-1, id=None),
 'metadata': {'meta_cols': {'mean_vmag': Value(dtype='float32', id=None),
   'phot_g_mean_mag': Value(dtype='float32', id=None),
   'e_phot_g_mean_mag': Value(dtype='float32', id=None),
   'phot_bp_mean_mag': Value(dtype='float32', id=None),
   'e_phot_bp_mean_mag': Value(dtype='float32', id=None),
   'phot_rp_mean_mag': Value(dtype='float32', id=None),
   'e_phot_rp_mean_mag': Value(dtype='float32', id=None),
   'bp_rp': Value(dtype='float32', id=None),
   'parallax': Value(dtype='float32', id=None),
   'parallax_error': Value(dtype='float32', id=None),
   'parallax_over_error': Value(dtype='float32', id=None),
   'pmra': Value(dtype='float32', id=None),
   'pmra_error': Value(dtype='float32', id=None),
   'pmdec': Value(dtype='float32', id=None)

In [14]:
api = wandb.Api()
run = api.run('AstroCLIPOptuna3/0r838fa4')

In [15]:
old_ds = PSMDataset(run.config, split='train')

In [34]:
len(old_ds)

17063

In [31]:
n = 1000

In [32]:
old_ds.mode = 'meta'

for i in tqdm(range(n)):
    old_ds[i]

100%|████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:00<00:00, 2076.94it/s]


In [33]:
old_ds.mode = 'spectra'

for i in tqdm(range(n)):
    old_ds[i]

100%|██████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:37<00:00, 26.41it/s]


In [29]:
old_ds.mode = 'photo'

for i in tqdm(range(n)):
    old_ds[i]

100%|███████████████████████████████████████████████████████████████████████████████| 200/200 [00:00<00:00, 381.77it/s]


In [30]:
old_ds.mode = 'all'

for i in tqdm(range(n)):
    old_ds[i]

100%|████████████████████████████████████████████████████████████████████████████████| 200/200 [00:02<00:00, 86.94it/s]


In [26]:
old_ds.mode

'all'

In [4]:
ds = load_dataset('MeriDK/AstroM3Processed', name='sub10_42')

In [36]:
for i in tqdm(range(n)):
    ds['train'][i]

100%|██████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:12<00:00, 83.13it/s]


In [6]:
hf = HFPSMDataset(ds, classes=CLASSES, seq_len=200, mode='meta', split='train')

In [7]:
len(hf)

1660

In [8]:
n = 100

In [9]:
hf.mode = 'meta'

for i in tqdm(range(n)):
    hf[i]

100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:03<00:00, 30.09it/s]


In [10]:
hf.mode = 'photo'

for i in tqdm(range(n)):
    hf[i]

100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:03<00:00, 29.14it/s]


In [11]:
hf.mode = 'spectra'

for i in tqdm(range(n)):
    hf[i]

100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:03<00:00, 28.27it/s]


In [57]:
hf.mode = 'all'
p, pm, s, m, l = hf[0]
p, pm, s

(array([[ 0.0000000e+00,  5.2961022e-01,  1.3599986e+00, ...,
          9.4999999e-01, -7.5696146e-01,  5.7815070e+00],
        [ 1.8481223e-02,  1.1410401e+00,  1.3714271e+00, ...,
          9.4999999e-01, -7.5696146e-01,  5.7815070e+00],
        [ 6.7646012e-02, -2.0401793e+01,  1.0628560e+00, ...,
          9.4999999e-01, -7.5696146e-01,  5.7815070e+00],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          9.4999999e-01, -7.5696146e-01,  5.7815070e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          9.4999999e-01, -7.5696146e-01,  5.7815070e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          9.4999999e-01, -7.5696146e-01,  5.7815070e+00]], dtype=float32),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.

In [14]:
hf_train_dataset[0][0].shape

(200, 9)

In [44]:
hf_train_dataset = HFPSMDataset(ds, classes=CLASSES, seq_len=200, split='train')
hf_val_dataset = HFPSMDataset(ds, classes=CLASSES, seq_len=200, split='validation')
hf_test_dataset = HFPSMDataset(ds, classes=CLASSES, seq_len=200, split='test')

In [114]:
for el in tqdm(hf_train_dataset):
    pass

100%|██████████████████████████████████████████████████████████████████████████████| 1660/1660 [01:10<00:00, 23.61it/s]


In [120]:
len(hf_train_dataset), len(hf_val_dataset), len(hf_test_dataset)

(17063, 2152, 2225)

In [121]:
api = wandb.Api()
run = api.run('meridk/AstroCLIPResults3/runs/3c2da15u')
config = run.config
config['use_wandb'] = False

In [122]:
train_dataset = PSMDataset(config, split='train')
val_dataset = PSMDataset(config, split='val')
test_dataset = PSMDataset(config, split='test')

In [143]:
df = pd.read_csv('/home/mariia/AstroML/data/asassn/preprocessed_data/full_lb/spectra_and_v_train.csv')

In [147]:
df.iloc[0][train_dataset.meta_cols].values.astype(np.float64)

array([ 1.4250000e+01,  1.4200958e+01,  8.6660000e-03,  1.4513055e+01,
        2.6188000e-02,  1.3729204e+01,  2.5066000e-02,  7.8385100e-01,
        7.5610000e-01,  1.4900000e-02,  5.0894300e+01,  3.8300000e-01,
        1.7000000e-02, -3.7070000e+00,  1.9000000e-02,  1.3194000e+01,
        3.5000000e-02,  1.3012000e+01,  4.2000000e-02,  1.2898000e+01,
        3.2000000e-02,  1.2717000e+01,  2.3000000e-02,  1.2743000e+01,
        2.4000000e-02,  1.2610000e+01,  9.4170000e+00,  2.9600000e-01,
       -2.6000000e-02,  3.1930000e+00,  3.7270000e+00,  1.0750000e+00,
        7.3889000e+01,  2.0469310e+01])

In [148]:
p, pm, s, m, l = train_dataset[0]
hp, hpm, hs, hm, hl = hf_train_dataset[0]

In [150]:
len(hm)

34

In [151]:
hm.dtype

dtype('float64')

In [138]:
hp, hpm, hs, hm, hl = hf_train_dataset[0]
hm.dtype

dtype('float64')

In [159]:
hs.shape

(3, 2575)

In [123]:
len(train_dataset), len(val_dataset), len(test_dataset)

(17063, 2152, 2225)

In [126]:
m

array([ 0.46845165,  0.5777532 ,  0.33702573,  0.48042554,  0.07711897,
        0.6222429 ,  0.5225165 , -0.5712912 , -0.08947697, -0.4166497 ,
        0.12132795,  0.13869835, -0.38648468,  0.1050081 , -0.29492944,
        0.6661094 ,  0.574305  ,  0.709537  ,  0.02201757,  0.7009008 ,
       -0.05441045,  0.66980654, -0.36477575,  0.6715334 , -0.34695286,
        0.8064633 ,  0.6847023 , -0.77802926, -0.22493474,  0.68248993,
       -0.45180646, -0.18078335,  1.0039113 ,  0.44424993], dtype=float32)

In [129]:
hm

array([ 0.46672255,  0.57648796,  0.35017371,  0.47926584,  0.08602203,
        0.62062323,  0.53369945, -0.57028121, -0.09175423, -0.41491431,
        0.11994488,  0.14183664, -0.38510299,  0.10614154, -0.29262456,
        0.66374785,  0.59276664,  0.70689768,  0.02273968,  0.69809496,
       -0.05366573,  0.66696525, -0.36622611,  0.66872674, -0.34343559,
        0.80092859,  0.68055969, -0.77459633, -0.22625332,  0.68076366,
       -0.45604378, -0.18119888,  1.00199795,  0.44220504])

In [60]:
l == hl

True

In [66]:
p.shape == hp.shape, pm.shape == hpm.shape, s.shape == hs.shape, m.shape == hm.shape

(True, True, True, True)

In [78]:
np.array_equal(p[:, :3], hp[:, :3]), np.array_equal(pm, hpm), np.array_equal(s, hs)

(False, True, True)

In [98]:
p[1, :3], hp[1, :3]

(array([0.01844262, 1.1410416 , 1.3714286 ], dtype=float32),
 array([0.01848122, 1.1410401 , 1.371427  ], dtype=float32))

In [79]:
p[:, :3][1], hp[:, :3][1]

(array([0.01844262, 1.1410416 , 1.3714286 ], dtype=float32),
 array([0.01848122, 1.1410401 , 1.371427  ], dtype=float32))

In [105]:
el = train_dataset.df.iloc[0]
p = train_dataset.get_vlc(el['name'])

In [106]:
hp = ds['train'][0]['photometry']

In [90]:
np.array_equal(p, hp)

False

In [91]:
p.dtype, hp.dtype

(dtype('float64'), dtype('float32'))

In [108]:
ds2 = load_dataset('MeriDK/AstroM3Dataset', name='sub10_42', trust_remote_code=True)
ds2 = ds2.with_format('numpy')

In [109]:
hp2 = ds2['train'][0]['photometry']

In [110]:
p[0], hp[0], hp2[0]

(array([2.45829176e+06, 1.15680000e+01, 2.41000000e-01]),
 array([2.4582918e+06, 1.1568000e+01, 2.4100000e-01], dtype=float32),
 array([2.4582918e+06, 1.1568000e+01, 2.4100000e-01], dtype=float32))

In [112]:
np.abs(p - hp) > 0.001

array([[ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ T

In [156]:
weights = torch.load("/home/mariia/AstroML/weights/2024-09-18-13-37-2wz4ysvn/weights-best.pth", weights_only=True)

In [158]:
weights.keys()

odict_keys(['logit_scale_ps', 'logit_scale_sm', 'logit_scale_mp', 'photometry_encoder.enc_embedding.value_embedding.tokenConv.weight', 'photometry_encoder.enc_embedding.position_embedding.pe', 'photometry_encoder.encoder.attn_layers.0.attention.query_projection.weight', 'photometry_encoder.encoder.attn_layers.0.attention.query_projection.bias', 'photometry_encoder.encoder.attn_layers.0.attention.key_projection.weight', 'photometry_encoder.encoder.attn_layers.0.attention.key_projection.bias', 'photometry_encoder.encoder.attn_layers.0.attention.value_projection.weight', 'photometry_encoder.encoder.attn_layers.0.attention.value_projection.bias', 'photometry_encoder.encoder.attn_layers.0.attention.out_projection.weight', 'photometry_encoder.encoder.attn_layers.0.attention.out_projection.bias', 'photometry_encoder.encoder.attn_layers.0.conv1.weight', 'photometry_encoder.encoder.attn_layers.0.conv1.bias', 'photometry_encoder.encoder.attn_layers.0.conv2.weight', 'photometry_encoder.encoder.at